apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-generator
  template:
    metadata:
      labels:
        app: data-generator
    spec:
      containers:
        - name: data-generator
          image: data-generator:latest   # Tilt will build this
          env:
            - name: KAFKA_BOOTSTRAP
              value: "kafka-service:9092"   # internal service for Kafka
