# JobManager service
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
spec:
  ports:
    - name: rpc
      port: 6123
    - name: blob
      port: 6124
    - name: ui
      port: 8081
  selector:
    app: flink
    component: jobmanager

---
# JobManager Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      containers:
        - name: jobmanager
          image: anomalies-detection:latest
          args: [
            "jobmanager",
            "--job-classname", "com.nashtech.demo.flink.AppMain",
            "/opt/flink/usrlib/retail-loss-prevention-1.0-SNAPSHOT.jar"
          ]
          ports:
            - containerPort: 6123
            - containerPort: 6124
            - containerPort: 8081
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: flink-jobmanager

---
# TaskManager Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
        - name: taskmanager
          image: anomalies-detection:latest
          args: ["taskmanager"]
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: flink-jobmanager
