{
 "title": "Anomalies",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Refund Anomalies",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"alertId\") FROM \"anomaly-alerts\" WHERE (\"type\" = 'REFUND_PATTERN') AND $timeFilter"
    }
   ]
  },
  {
   "title": "Refund Anomalies",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "SELECT \"message\", \"employId\", \"riskScore\", \"storeId\" FROM \"anomaly-alerts\" WHERE (\"type\" = 'REFUND_PATTERN') AND $timeFilter"
    }
   ]
  },
  {
   "title": "Total Shrinkage anomalies",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT count(\"alertId\") FROM \"anomaly-alerts\" WHERE (\"type\" = 'SHRINKAGE') AND $timeFilter"
    }
   ]
  },
  {
   "title": "Shrinkage Anomalies",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "SELECT \"message\", \"employId\", \"riskScore\", \"storeId\" FROM \"anomaly-alerts\" WHERE (\"type\" = 'SHRINKAGE') AND $timeFilter"
    }
   ]
  },
  {
   "title": "Total Security Correlation Anomalies",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"alertId\") FROM \"anomaly-alerts\" WHERE (\"type\" = 'SECURITY_CORRELATION') AND $timeFilter"
    }
   ]
  },
  {
   "title": "Security Anomalies",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "SELECT \"message\", \"employId\", \"riskScore\", \"storeId\" FROM \"anomaly-alerts\" WHERE (\"type\" = 'SECURITY_CORRELATION') AND $timeFilter"
    }
   ]
  }
 ]
}