apiVersion: v1
kind: ConfigMap
metadata:
  name: influx-sink-connector
data:
  influx-sink.json: |
    {
      "name": "influx-sink",
      "config": {
        "connector.class": "io.confluent.influxdb.InfluxDBSinkConnector",
        "tasks.max": "1",
        "topics": "anomaly-alerts",
        "influxdb.url": "http://influxdb.default.svc.cluster.local:8086",
        "influxdb.db": "alerts",
        "influxdb.username": "admin",
        "influxdb.password": "admin123",
        "measurement.name.format": "${topic}",
        "key.converter": "org.apache.kafka.connect.storage.StringConverter",
        "value.converter": "org.apache.kafka.connect.storage.StringConverter"
      }
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: register-influx-sink
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: register
          image: curlimages/curl:8.5.0
          command: ["/bin/sh","-c"]
          args:
            - |
              set -e 
              until curl -s http://kafka-connect.default.svc.cluster.local:8083/connectors > /dev/null; do
              echo "Waiting for Kafka Connect REST API..."
                sleep 5
              done
              echo "Registering InfluxDB Sink Connector..."
              curl -s -X POST http://kafka-connect.default.svc.cluster.local:8083/connectors \
                -H "Content-Type: application/json" \
                --data @/config/influx-sink.json \
                | sed -e 's/.*/[CONNECT] &/'
          volumeMounts:
            - name: connector-config
              mountPath: /config
      volumes:
        - name: connector-config
          configMap:
            name: influx-sink-connector
